[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # Do not force - let Netlify serve real assets when present. For SPA fallback,
  # status = 200 is sufficient and will not override existing files.
